---
galaxy_info:
  author: pha@tiatechnology.com
  description: Manages the internal and external loadbalancers, creates listeners and default actions/rules
  company: TIA

  platforms:
    - name: Oracle Linux
      versions:
        - 7

  license: MIT

  min_ansible_version: 2.7

dependencies: []