---
- name: Assume non-admin sts role
  include_role:
    name: aws_sts_login
  vars:
    admin_access_key: "{{ aws_credentials_vault[cust_config[cust_name][env_name]['aws_profile'].admin_role_name].access_key }}"
    admin_secret_access_key: "{{ aws_credentials_vault[cust_config[cust_name][env_name]['aws_profile'].admin_role_name].secret_access_key }}"
    assume_role_arn: "{{ aws_credentials_vault[cust_config[cust_name][env_name]['aws_profile'].role_name].role_arn }}"
    assume_role_session_name: "ansible-{{ mode }}-{{ role_name }}"

- block: # In delete mode only.
  # Collect a list of active s3 buckets, to determine whether the S3 bucket need cleaning up.
  - name: aws_s3_bucket_facts
    aws_s3_bucket_facts:
      aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
      aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
      security_token: "{{ assumed_role.sts_creds.session_token }}"
    register: s3_buckets

  - name: "Delete all Static Web files (and bucket) in: cussp-{{ cust_config[cust_name][env_name].account }}"
    aws_s3:
      aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
      aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
      security_token: "{{ assumed_role.sts_creds.session_token }}"
      bucket: "cussp-{{ cust_config[cust_name][env_name].account }}"
      mode: delete
    when: (s3_buckets.ansible_facts.buckets |  selectattr('name','equalto',  'cussp-' + cust_config[cust_name][env_name].account ) ) | list # true when list isn't empty

  - name: "Delete all objects (and bucket) in: cussp-{{ cust_config[cust_name][env_name].account }}-logs"
    aws_s3:
      aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
      aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
      security_token: "{{ assumed_role.sts_creds.session_token }}"
      bucket: "cussp-{{ cust_config[cust_name][env_name].account }}-logs"
      mode: delete
    when: (s3_buckets.ansible_facts.buckets |  selectattr('name','equalto',  'cussp-' + cust_config[cust_name][env_name].account + '-logs') ) | list # true when list isn't empty
  when: mode|lower == 'delete'

- name: "{{ mode }} general storage S3 buckets"
  cloudformation:
    stack_name: "CuSSP-s3-{{ cust_config[cust_name][env_name].account }}-bucket"
    state: "{{ stack_state }}"
    aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
    security_token: "{{ assumed_role.sts_creds.session_token }}"
    region: "{{ role_region }}"
    template: "{{ script_dir }}/s3-cussp-bucket.yml"
    template_parameters:
      BucketName: "cussp-{{ cust_config[cust_name][env_name].account }}"
