---
- name: "{{ mode }} rds-subnet-group"
  cloudformation:
    stack_name: "{{ rds_subnet_stack_name }}"
    state: "{{ stack_state }}"
    aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
    security_token: "{{ assumed_role.sts_creds.session_token }}"
    region: "{{ role_region }}"
    template: "{{ rdb_script_dir }}/rds-subnetgroup.yml"
    template_parameters:
      NetworkStack: "{{ network_stack_name }}"
      IntranetStack: "{{ intranet_stack_name }}"

- name: "{{ mode }} rds-parameter-group"
  cloudformation:
    stack_name: "{{ rds_parametergroup_stack_name }}"
    state: "{{ stack_state }}"
    aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
    security_token: "{{ assumed_role.sts_creds.session_token }}"
    region: "{{ role_region }}"
    template: "{{ rdb_script_dir }}/rds-parametergroup.yml"