---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Roles for Fargate Instances"

Resources:

  # A role so that our ECS Fargate Services can work with other AWS services
  EcsNode:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: ecsTaskExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        # Allows ECS tasks to call AWS services on your behalf.
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
