---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Manage Secrets in an instance of SSM"

Parameters:
  MySecretString:
    Type: String
    Description: "json string or path to policy string"

  SecretId:
    Type: String
    Description: Secret Value to access artifactory

  RoleName:
    Type: String
    Description: friendly name of role to add permissions to.

  TaskExecutionRoleName:
    Type: String
    Description: Role name used by Fargate tasks.

Resources:
  SecretManagerAccessOps:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy to grant permissions to access secretmanager and create update secrets
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'secretsmanager:*'
            Resource: '*'
      Roles:
        - !Ref RoleName

  SecretManagerEcsTaskExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Secretsmanager read artifactory image
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'secretsmanager:GetSecretValue'
            Resource: !Sub "arn:aws:secretsmanager:*:${AWS::AccountId}:secret:*"
      Roles:
        - !Ref TaskExecutionRoleName

  ArtifactorySecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: "secret for accessing artifactory"
      Name: !Ref SecretId
      SecretString: !Ref MySecretString





