---
galaxy_info:
  author: pha@tiatechnology.com
  description: Manages access to s3 buckets situated in admin account
  company: TIA

  platforms:
    - name: Oracle Linux
      versions:
        - 7

  license: MIT

  min_ansible_version: 2.7

dependencies: []
