---
AWSTemplateFormatVersion: "2010-09-09"
Description: "RDS parametergroup for Microservice"

Resources:
  RDSDBParameterGroup:
    Type: "AWS::RDS::DBParameterGroup"
    Properties:
      Description: "Parameter Group for CuSSP"
      Family: mysql5.7
      Parameters:
        log_bin_trust_function_creators: 1
        max_allowed_packet: 31457280
        max_connections: 2000
        character_set_client: utf8mb4
        character_set_connection: utf8mb4
        character_set_database: utf8mb4
        character_set_filesystem: utf8mb4
        character_set_results: utf8mb4
        character_set_server: utf8mb4
        collation_connection: utf8mb4_general_ci
        collation_server: utf8mb4_general_ci

  RDSDBParameterGroup8:
    Type: "AWS::RDS::DBParameterGroup"
    Properties:
      Description: "Parameter Group for CuSSP"
      Family: mysql8.0
      Parameters:
        log_bin_trust_function_creators: 1
        max_allowed_packet: 31457280
        max_connections: 2000
        character_set_client: utf8mb4
        character_set_connection: utf8mb4
        character_set_database: utf8mb4
        character_set_filesystem: utf8mb4
        character_set_results: utf8mb4
        character_set_server: utf8mb4
        collation_connection: utf8mb4_general_ci
        collation_server: utf8mb4_general_ci
Outputs:
  ParameterGroup:
      Description: "Reference to ParameterGroup"
      Value:  !Ref RDSDBParameterGroup
      Export: # export the ID of the ParameterGroup so other stacks can import it
        Name: !Sub ${AWS::StackName}-DBParameterGroup

  ParameterGroup8:
      Description: "Reference to mysql 8 ParameterGroup"
      Value:  !Ref RDSDBParameterGroup8
      Export: # export the ID of the ParameterGroup so other stacks can import it
        Name: !Sub ${AWS::StackName}-DBParameterGroup8
