---
# AWS ELB setup.
# This playbook can be used to both create or delete the elb stacks.
- name: Elastic load balancer set up
  hosts: localhost
  vars_files:
    - "{{ '../vars/cust/cust_' + cust_name + '.yml' }}"
  vars:
    var_role_region: "{{ cust_config[cust_name][env_name]['aws_profile'].region }}"

  tasks:
    - name: Validate cust_name/env_name
      assert:
        that:
          - cust_name is defined
          - env_name is defined
        fail_msg: "vars 'cust_name' and 'env_name' are required"

    - name: Validate mode
      assert:
        that:
          - "mode == 'create' or mode == 'delete'"
        fail_msg: "mode var must be either 'create' or 'delete'. ie -e 'mode=create'"

    - name: "{{ mode }} loadbalancer for aws"
      include_role:
        name: aws_loadbalancer
      vars:
        role_region: "{{ var_role_region }}"
        log_bucket_name: "cussp-{{ cust_config[cust_name][env_name].account }}-logs"