---
# AWS networking. This playbook can be used to both Create or delete the network stacks. Passing either Create or delete as an extra var.
- name: AWS networking
  hosts: localhost
  vars_files:
    - "{{ '../vars/cust/cust_' + cust_name + '.yml' }}"
  vars:
    var_role_region: "{{ cust_config[cust_name][env_name]['aws_profile'].region }}"

  tasks:
    - name: Validate cust_name/env_name
      assert:
        that:
          - cust_name is defined
          - env_name is defined
        fail_msg: "vars 'cust_name' and 'env_name' are required"

    - name: Validate mode
      assert:
        that:
          - "mode == 'create' or  mode == 'delete'"
        fail_msg: "mode var must be either 'create' or 'delete'. ie -e 'mode=create'"

    - name: "{{ mode }} aws networking"
      include_role:
        name: aws_networking
      vars:
        customer_ipv4_address: "{{ cust_config[cust_name][env_name]['aws_network'].customer_ipv4_address }}"
        vpc_cidr_prefix: "{{ cust_config[cust_name][env_name]['aws_network'].vpc_cidr_prefix }}"
        dest_cidr_block: "{{ cust_config[cust_name][env_name]['aws_network'].dest_cidr_block }}"
        role_region: "{{ var_role_region }}"
