- name: Manage Secret
  hosts: localhost
  vars_files:
    - "{{ '../vars/cust/cust_' + cust_name + '.yml' }}"
    - "../vars/aws/credentials_vault.yml"

  tasks:
    - name: Validate cust_name/env_name
      assert:
        that:
          - cust_name is defined
          - env_name is defined
        fail_msg: "vars 'cust_name' and 'env_name' are required"

    - name: Validate mode
      assert:
        that:
          - "mode == 'create' or  mode == 'delete'"
        fail_msg: "mode var must be either 'create' or 'delete'. ie -e 'mode=create'"


    - name: "{{ mode }} aws secret"
      include_role:
        name: aws_secret
      vars:
        role_region: "{{ cust_config[cust_name][env_name]['aws_profile'].region }}"
        artifactory_username: "{{ credentials_vault['repo.tiatechnology.com'].username }}"
        artifactory_password: "{{ credentials_vault['repo.tiatechnology.com'].password }}"
        stack_state: "{{ 'present' if mode|lower == 'create' else 'absent' }}"
