---
- name: "{{ mode  }} Internet Gateway and Route Table for public traffic for Customer Self Service Portal"
  cloudformation:
    stack_name: "{{ internet_stack_name }}"
    state: "{{ stack_state }}"
    aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
    security_token: "{{ assumed_role.sts_creds.session_token }}"
    region: "{{ role_region }}"
    template: "{{ script_dir }}/internet.yml"
    template_parameters:
      NetworkStack: "{{ vpc_network_stack_name }}"