---
- name: "{{ mode }} VPN Gateway and Route Table for intranet traffic for Customer Self Service Portal"
  cloudformation:
    stack_name: "{{ intranet_stack_name }}"
    state: "{{ stack_state }}"
    aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
    security_token: "{{ assumed_role.sts_creds.session_token }}"
    region: "{{ role_region }}"
    template: "{{ script_dir }}/intranet.yml"
    template_parameters:
      NetworkStack: "{{ vpc_network_stack_name }}"
      CustomerIpV4Address: "{{ customer_ipv4_address }}"
      DestinationCidrBlock: "{{ dest_cidr_block }}"
      BgpAsn: 65000