---
- name: "{{ mode }} Network ACLs for public traffic for Customer Self Service Portal"
  cloudformation:
    stack_name: "{{ internet_security_stack_name }}"
    state: "{{ stack_state }}"
    aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
    security_token: "{{ assumed_role.sts_creds.session_token }}"
    region: "{{ role_region }}"
    template: "{{ script_dir }}/internet-security.yml"
    template_parameters:
      NetworkStack: "{{ vpc_network_stack_name }}"

- name: "{{ mode }} Network ACLs for private intranet traffic for Customer Self Service Portal"
  cloudformation:
    stack_name: "{{ intranet_security_stack_name }}"
    state: "{{ stack_state }}"
    aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
    security_token: "{{ assumed_role.sts_creds.session_token }}"
    region: "{{ role_region }}"
    template: "{{ script_dir }}/intranet-security.yml"
    template_parameters:
      NetworkStack: "{{ vpc_network_stack_name }}"
      IntranetCidrBlock: "{{ dest_cidr_block }}"