---
- name: "{{ mode }} vpc with cloudformation"
  cloudformation:
    stack_name: "{{ vpc_network_stack_name }}"
    state: "{{ stack_state }}"
    aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
    security_token: "{{ assumed_role.sts_creds.session_token }}"
    region: "{{ role_region }}"
    template: "{{ script_dir }}/network.yml"
    template_parameters:
      VpcCidrPrefix: "{{ vpc_cidr_prefix }}"
      DnsName: "{{ local_dns_name }}"