---
AWSTemplateFormatVersion: 2010-09-09
Description: Elasticsearch linked service role

Resources:
  ElasticsearchLinkedRole:
    Type: AWS::IAM::ServiceLinkedRole
    Properties:
      AWSServiceName: es.amazonaws.com
      Description: required to allow elastic search access to vpc